# fly.toml app configuration file generated for esa-prod on 2025-03-27T16:17:44+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'esa-prod'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
